### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by bjsi** [catppuccin/remnote#2]
@justTOBBI 

Excellent work, these themes look really good! Here are a couple of suggestions. If you make changes, don't forget to re-upload! Are you on the RemNote Discord? Let me know your Discord ID and I'll give you the extension-developer role :)

1) Small bug when the UI fades after typing in a document:

![image](https://user-images.githubusercontent.com/58147075/216554670-7485b65b-8a3b-42f9-948b-4fb9c172349e.png)

https://github.com/catppuccin/remnote/blob/0296af8ae56e75fd8934469fb96ba884769f0fa4/frapp%C3%A9/theme.css#L74-L76

You can change this line in each theme to `var(--base)!important` to fix this.

2) Consider making the themes available on mobile if they work.

https://github.com/catppuccin/remnote/blob/0296af8ae56e75fd8934469fb96ba884769f0fa4/frapp%C3%A9/manifest.json#L7

3) Consider adding a logo.png to the zip file. It will get displayed here:
![image](https://user-images.githubusercontent.com/58147075/216558985-765918fa-2ff0-4785-bd05-1fc9e1670883.png)

**Comment by justTOBBI** [comment]
Hey,
the feedback is very much appreciated and if @coldenate isn't against it, I would tackle these Issues in the next couple days.
Thank you very much for taking a look at this :D
 ![image](https://cdn.discordapp.com/emojis/1004920394890874932.webp?size=100&quality=lossless)

**Comment by coldenate** [comment]
Yes! For sure! @bjsi I am happy to also tackle these issues soon.
Thank you for offering, our ids are 386829409438531595, 338107857486610433.
Most of the packaging was done locally, so I may try and tinker with some automation. For now, I'll stick to traditional methods :).

**Comment by coldenate** [comment]
> Consider making the themes available on mobile if they work.

I will further look into this, but I think that was my mistake labeling it as incompatible with mobile! Currently, all the bugs discovered have parity across device types. Thank you for pointing the manifest file out! 😅 @bjsi

**Comment by justTOBBI** [comment]
Hey, I just pushed the changes pointed out in your issue.
@coldenate, it would be awesome if you could add the logo to the marketplace, since I really don't know how to do that lmao

**Comment by coldenate** [comment]
Sure! I will get that done. On my branch, the suggested !important change seemed to not fix the issue. Did it work in your instance? @justTOBBI

**Comment by coldenate** [comment]
I can double confirm that the change doesn't fix what I presume as the "Zen Mode" error. I am planning on reworking the whole repo to align with the successful themes already on the market.

**Comment by justTOBBI** [comment]
So yeh, I didnt really test it out, since my Remnote was slow af when I tried to remove the old CSS and added the new, so I just added the change bjsi suggested.

**Comment by coldenate** [comment]
I'm starting to notice a trend with many other themes on the marketplace also having this issue. I'm going to ask around on the Discord tomorrow, and I'll see if I need to open a support ticket. 
![image](https://user-images.githubusercontent.com/66754842/219701850-2ef49d8f-d9b9-43bb-b3f1-a88ff44dcc1c.jpeg)
![image](https://user-images.githubusercontent.com/66754842/219702327-1cc690bc-79c9-4c72-8cb1-3e2e33eb35af.jpeg)

@bjsi Have you heard of this issue with Zen Mode from anyone before?

**Comment by coldenate** [comment]
Rightyo! I fixed up the issues with many thanks to @akirathesquid, and I pushed them to a pr.

**Comment by coldenate** [comment]
Hi @bjsi, I have a question about how the theming works 😅  ...
 Will I be able to bundle the `palette_values.css` and import them from `theme.css` even though `theme.css` contains the actual theme assignments? 
does it have to be monofile?
